### ISSUE TITLE
Number of motifs found by examples/motif.rs may be underestimated

### ISSUE THREAD

**Issue by jmftrindade** [frankmcsherry/dataflow-join#1]
I'm trying out a few examples after reading [your blog post on tracking motifs](https://github.com/frankmcsherry/blog/blob/master/posts/2016-09-17.md), and unless I'm doing something wrong, it looks like the number of motifs found by `examples/motif.rs` may be underestimated.

Using the same livejournal dataset from the blog, and with a "single directed edge" motif, I get results that are a lot smaller than the expected (which I believe should match the number of edges in the graph, or at least be somewhat close to it):

```
$ wc -l /data/soc-LiveJournal1.txt
 68993777 /data/soc-LiveJournal1.txt
$ cargo run --release --example motif -- 1 0 1 /data/soc-LiveJournal1.txt 68000000 1000 inspect
(...)
elapsed: Duration { secs: 22, nanos: 760898251 }	total motifs at this process: 993777

$ wc -l /data/soc-LiveJournal1-1000.txt
    1000 /data/soc-LiveJournal1-1000.txt
$ cargo run --release --example motif -- 1 0 1 /data/soc-LiveJournal1-1000.txt 1000 1000 inspect
(...)
elapsed: Duration { secs: 0, nanos: 1657901 }	total motifs at this process: 4
``` 

In the first case, for the livejournal graph with close to 69 million edges, the example found less than 1 million "single directed edge" motifs.  For a chunk of the same graph which contains only the first 1k edges, it found only 4 instances of that same motif.

The reason why I started looking at these simple "single directed edge" motifs was because I was trying to debug a feed-forward-loop and other slightly more complex motifs.  In particular, I have a few synthetic graphs, which I know contain the motifs I'm looking for, but that `example/motif.rs` fails to find.  Please advise, thanks! --Joana

**Comment by frankmcsherry** [comment]
I'll check it out and report back! As weird as it sounds, this (one edge) is a case we did not test. :)

**Comment by frankmcsherry** [comment]
Aha, wait I think I see the issue:

```
$ cargo run --release --example motif -- 1 0 1 /data/soc-LiveJournal1.txt 68000000 1000 inspect
(...)
elapsed: Duration { secs: 22, nanos: 760898251 }	total motifs at this process: 993777
```

The command-line argument `68000000` says "pre-load the first 68,000,000 edges, and go from there", so these 68 million edges get loaded up and then the *remaining* matches are what get reported back at you. At this point you only get 993,777 matches, because there are exactly 68,993,777 edges in the input file. It should be that if you replace the 68000000 with 0, you'll see the total edge count.

```
echidnatron% cargo run --release --example motif -- 1 0 1 ~/Projects/Datasets/soc-LiveJournal1.txt 0 1000 inspect
(...)
elapsed: Duration { secs: 85, nanos: 883273675 }	total motifs at this process: 68993773
echidnatron% 
```

I have to admit to being unclear why, after loading 1,000 edges of a file with 1,000 edges in it, you still see four additional matches.

**Comment by frankmcsherry** [comment]
As a quick comment to prevent head-scratching on your part, there is an outstanding and probably undocumented bug at the moment with symmetric edge constraints, so if you had a motif

```
2 0 1 1 0
```

it won't work correctly. It never came up in our experiments, so it never got fixed, but it is definitely wrong.

**Comment by jmftrindade** [comment]
Ah, that makes sense, thank you!  Nice that even though you guys hadn't tested the single edge case, it still gives you an exact match.

I just looked at the file that *I thought* had 1,000 edges, but it actually has 996 edges, as the first 4 lines on `soc-LiveJournal1.txt` are comments (I had just `head -n 1000` on it to get the "1,000" edges version).  Maybe a bug on processing comments when looking for single edge motifs?

Do you have an idea on what the root cause might be for the bug with symmetric edge constraints?  I could try and take a look as a way to get more familiar with the code.

**Comment by frankmcsherry** [comment]
The bug on symmetric edge constraints is:

The logic for incremental motif updates takes each relation in the motif, and for each change to that relation it determines the join with the other relations by extending the initial change. So if the edge relation gets a `((src, dst), +1)` update, we try and add various bindings to the first two bindings of `(src, dst)`.

What this ignores is that there should be a *filtering* step as well, when there are symmetric edge constraints. That is, if we see `((src, dst), +1)` before getting too excited we should see if this change should even be developed; it may be that `(dst, src)` does not exist in the relation imposing a symmetric constraint.

There is a not-hard fix one could do where instead of starting from `(src, dst)` on edge changes we can start with a candidate single proposed extension of `(src, [dst])` and intersect it with the other proposal from the symmetric constraint (using the same machinery that already exists, but which is probably over-engineered for asking the single question "does `(dst, src)` exist?").

There are neater fixes one could imagine where the `PrefixExtender` trait could be implemented by other types with perhaps simpler implementations (others one could imagine: functional dependence, antijoin, .. maybe others?).

It would totally be instructive to ponder "ok, ok, how would that work?" as you read, but I don't know that I would recommend actually doing it, unless you are seriously under-utilized at the moment (or if you have a personal interest in having it work).
